### ISSUE TITLE
Error: Unauthorized in parse-server-migration

### ISSUE THREAD

**Issue by nconfrey** [MoralisWeb3/Moralis-JS-SDK#1036]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

I'm completing the steps [detailed in the tutorial for the Parse Server Migration](https://v1docs.moralis.io/moralis-dapp/getting-started/self-hosting-moralis-server/local-environment-setup) and when I'm running my server at `http://localhost:1337/server` I'm only getting Unauthorized as a result:

`{"error":"unauthorized"}`

When I hook up my frontend to this localhost server, all my Moralis queries fail with 403 Forbidden.

### Steps + code to reproduce

Even the [screenshots in the tutorial have the error unauthorized (scroll to the bottom)](https://v1docs.moralis.io/moralis-dapp/getting-started/self-hosting-moralis-server/deployment).

Following the steps in the tutorial, plugging in my keys into the `.env` file leads to a 403 Forbidden.

**Comment by ErnoW** [comment]
This is expected behaviour and is how parse-server works. When you see `{"error":"unauthorized"}` then it means that the server is up and running. See https://community.parseplatform.org/t/error-unauthorized-when-run-parse-server/2635 for more info.

The 403 error can have different causes. I have too little info to help you on it. I verified with the example react app (https://v1docs.moralis.io/moralis-dapp/getting-started/self-hosting-moralis-server/client-connection) and works without the 403 error.

If you are still stuck then I would advise to test with the example React app, and check if that works. Or search/ask on [the Moralis Forums](https://forum.moralis.io/) for more help. More people are available on the forums to help you out.

Closing this issue as this is expected behaviour on parse-server-migration demo.
