### ISSUE TITLE
Moralis.User.me is missing from types definition

### ISSUE THREAD

**Issue by vmohan7** [MoralisWeb3/Moralis-JS-SDK#269]
### Checklist

- [ X ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ X ] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [ X ] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

For typescript, Moralis.User.me is missing from the definition and is thus not useable in typescript unless the object is converted to an any type. 

### Steps + code to reproduce

Setup typescript and try to call Moralis.User.me, which results in the compile error "Property 'me' does not exist on type 'UserConstructor'"

### Actual Outcome

method description for me

### Expected Outcome

Add me to the type definition

### Environment

Node JS Typescript

Server

- Moralis server version: `0.0.176`

**Comment by ErnoW** [comment]
Will be fixed in the next release: https://github.com/MoralisWeb3/Moralis-JS-SDK/pull/275

Please not that this release will be a major version bump for you with breaking changes (from 0.0.184 to 1.0.0). So if you upgrade you should check the migration guide: https://forum.moralis.io/t/moralis-js-sdk-v1-0-migration-to-ethers-js/8041

Alternatively, you can manually typecast it. This is the Typedefinition:
```js
interface UseMasterKeyOption {
    /**
     * In Cloud Code and Node only, causes the Master Key to be used for this request.
     */
    useMasterKey?: boolean;
}
me<T extends Moralis.User>(sessionToken: string, options?: UseMasterKeyOption): Promise<T>;
```

**Comment by vmohan7** [comment]
Works for me and tested on 1.3.. Thanks!
